src/models/Comments.py
from main import db
from datetime import datetime


class Comments(db.Model):
    __tablename__ = "comments"

    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, nullable=False, default=datetime.now)
    comment = db.Column(db.Text, nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey("posts.id"), nullable=True)
    profile_id = db.Column(
        db.Integer, db.ForeignKey("profile.id"), nullable=True)

    def __repr__(self):
        return f"Comment: {self.id}"

src/models/Groups.py
from main import db
from models.Locations import Location
from models.Posts import Posts


class Groups(db.Model):
    __tablename__ = "groups"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(), nullable=False, unique=False)
    description = db.Column(db.Text, nullable=True, unique=False)
    location = db.relationship(
        Location, backref="group", lazy="dynamic",
        cascade="all, delete, delete-orphan", passive_deletes=True)
    members = db.relationship(
        "GroupMembers", backref="groups",
        cascade="all, delete, delete-orphan", passive_deletes=True)
    posts = db.relationship(
        Posts, backref="group", lazy="dynamic",
        cascade="all, delete, delete-orphan", passive_deletes=True)

    def __repr__(self):
        return f"Group: {self.id}"

src/models/Locations.py
from main import db


class Location(db.Model):
    __tablename__ = "locations"

    id = db.Column(db.Integer, primary_key=True)
    postcode = db.Column(db.Integer, nullable=False)
    suburb = db.Column(db.String(), nullable=False)
    state = db.Column(db.String(), nullable=False)
    profile_id = db.Column(
        db.Integer, db.ForeignKey("profile.id"), nullable=True)
    group_id = db.Column(db.Integer, db.ForeignKey(
        "groups.id", ondelete="CASCADE"), nullable=True)

    def __repr__(self):
        return f"Location: {self.id}"

src/controllers/group_controller.py
from models.Profile import Profile
from models.ProfileImage import ProfileImage
from models.Groups import Groups
from models.Locations import Location
from models.Group_members import GroupMembers
from models.Posts import Posts
from models.Comments import Comments
from schemas.LocationSchema import location_schema
from controllers.controller_helpers import Helpers
from main import db
from flask import (
    Blueprint, render_template, flash, redirect, url_for, request, abort)
from flask_login import login_required
from forms import (
    CreateGroup, SearchLocation, UpdateGroup, UpdateButton, JoinButton,
    UnjoinButton, DeleteButton, SearchForm)
import json
from sqlalchemy import or_, desc

groups = Blueprint("groups", __name__, url_prefix="/web/groups")


@groups.route("/", methods=["GET"])
@login_required
def groups_page():
    """
    Groups page with My groups and Group recommendation sections.
    """
    user_id, profile = Helpers.retrieve_profile()
    form = JoinButton()
    form2 = UnjoinButton()
    form3 = DeleteButton()

    # My Groups section logic - Groups that the active user is currently
    # a member of.
    groups = Groups.query.with_entities(
        Profile.id, GroupMembers.admin, Groups.id,
        Groups.name, Groups.description, Location.postcode, Location.suburb,
        Location.state).select_from(Profile).filter_by(
            id=profile.id).outerjoin(GroupMembers).join(
                Groups).join(Location).all()

    # Group recommendations section logic. Retrieves and displays groups that
    # is not associated with the current user's profile but has a group
    # postcode that is associated with the active user's profile.
    member = []
    non_member = []
    locations = []
    recommendations = []
    # Get user's groups
    for group in groups:
        member.append(Groups.query.get(group.id))
    # Get groups that user is not a member of
    for group in Groups.query.all():
        if group not in member:
            non_member.append(group)
    # Get postcodes associated to user's profile
    for location in Location.query.filter_by(profile_id=profile.id):
        locations.append(location.postcode)

    # Find non-member group postcodes that matches postcodes associated
    # with user's profile
    for group in non_member:
        query = Groups.query.with_entities(
            Groups.id, Groups.name, Location.postcode, Location.suburb,
            Location.state).filter_by(id=group.id).filter(
                Location.postcode.in_(locations)).join(
                    Location).first()
        recommendations.append(query)
    return render_template(
        "groups.html", groups=groups, recommendations=recommendations,
        form=form, form2=form2, form3=form3)


@groups.route("/create", methods=["GET", "POST"])
@login_required
def create_group():
    """
    Create group page

    GET requests renders group creation page
    POST requests handles validation of group creation forms and group
    creation logic in two steps - Location search followed by group details.
    """
    user_id, profile = Helpers.retrieve_profile()

    form = SearchLocation()
    form2 = CreateGroup()
    form2.group_location.choices = None
    data = None

    # Step 1: Postcode search using external API and re-render page with valid
    # location options to be associated to a new group as a dynamic choices
    # field in form2.
    if form.validate_on_submit():
        data = Helpers.location_search(form.postcode.data)
        if not data:
            flash("Not a valid postcode")
        elif data:
            group_locations = [
                (index, (location["name"], location["state"]["abbreviation"]))
                for index, location in enumerate(data)]
            form2.group_location.choices = group_locations
        return render_template(
            "create_group.html", form=form, form2=form2, data=data)

    # Step2: User prompted to enter required group details for group creation
    if form2.is_submitted():
        # Required to pass group location options to variable from template
        form2.group_location.choices = request.args["locations"]
        data = request.args.to_dict(flat=False)
    if form2.validate_on_submit():
        # converts selected location option into json
        location = data["data"][int(form2.group_location.data)]
        location = location.replace("'", '"')
        location = json.loads(location)

        # Group creation logic
        new_group = Groups()
        new_group.name = form2.group_name.data
        new_group.description = form2.group_description.data

        # Group location logic
        new_location = Location()
        new_location.postcode = location["postcode"]
        new_location.suburb = location["name"]
        new_location.state = location["state"]["abbreviation"]
        new_group.location.append(new_location)

        # Establishes active profile as newly created group's admin
        GroupMembers(group=new_group, profile=profile, admin=True)
        db.session.add(new_group, new_location)
        db.session.commit()
        flash("Group created!")
        return redirect(url_for("groups.groups_page"))
    return render_template(
        "create_group.html", form=form, form2=form2, data=data)


@groups.route("/<int:id>", methods=["GET"])
@login_required
def group_details(id):
    """
    Group Details page displaying group details, posts and comments
    """
    user_id, profile = Helpers.retrieve_profile()
    form = DeleteButton()

    group = Groups.query.with_entities(
        Groups.name, Groups.description, Location.postcode, Location.suburb,
        Location.state).filter_by(id=id).join(Location).first()
    group_name = group.name
    group_description = group.description
    group_location = f"{group.suburb}, {group.state}"

    posts = Posts.query.with_entities(
        Posts.id, Profile.name, Posts.post, Posts.profile_id,
        ProfileImage).select_from(Posts).join(Profile).join(
            ProfileImage).filter(Posts.group_id == id).order_by(
                desc(Posts.date)).all()
    data = []
    for post in posts:
        image = Helpers.retrieve_profile_picture(post[4])

        post_comments = Comments.query.with_entities(
            Comments.id, Comments.comment, Profile.name,
            ProfileImage).select_from(Comments).join(Profile).join(
                ProfileImage).filter(Comments.post_id == post.id).order_by(
                    desc(Comments.date)).all()
        comments_data = []
        for comment in post_comments:
            comment_img = Helpers.retrieve_profile_picture(comment[3])
            comments_data.append((comment, comment_img))
        data.append((post, image, comments_data))

    return render_template(
        "group_detail.html", group_name=group_name,
        group_description=group_description, group_location=group_location,
        id=id, data=data, profile_id=profile.id, form=form)


@groups.route("/<int:id>/update", methods=["GET", "POST"])
@login_required
def update_group(id):
    """
    Group details update page

    GET requests renders group update page
    POST requests validates group update form and handles group update logic.
    """
    user_id, profile = Helpers.retrieve_profile()
    form = UpdateGroup()

    admin_check = GroupMembers.query.filter_by(
        group_id=id, profile_id=profile.id, admin=True).first()
    if not admin_check:
        return abort(401, description="Not authorised to update group")

    group_location = Location.query.filter_by(group_id=id).first()
    group = Groups.query.filter_by(id=id).first()

    if form.validate_on_submit():
        if not form.group_name.data and form.group_description.data:
            group.description = form.group_description.data
        elif form.group_name.data and not form.group_description.data:
            group.name = form.group_name.data
        elif not form.group_name.data and not form.group_description.data:
            flash("Group not updated")
            return redirect(url_for("groups.groups_page", id=id))
        else:
            group.name = form.group_name.data
            group.description = form.group_description.data
        db.session.commit()
        flash("Group updated")
        return redirect(url_for("groups.groups_page", id=id))

    return render_template(
        "update_group.html", form=form, id=id, location=group_location)


@groups.route("/<int:id>/location", methods=["GET", "POST"])
@login_required
def update_group_location(id):
    """
    Update group location page.

    GET requests renders group location update page.
    POST requests validates location search form and location search
    on external API.
    """
    user_id, profile = Helpers.retrieve_profile()

    admin_check = GroupMembers.query.filter_by(
        group_id=id, profile_id=profile.id, admin=True).first()
    if not admin_check:
        return abort(401, description="Not authorised to update group")

    form = SearchLocation()
    form2 = UpdateButton()

    if form.validate_on_submit():
        data = Helpers.location_search(form.postcode.data)
        return render_template(
            "group_location.html", id=id, form=form, data=data, form2=form2)
    return render_template(
        "group_location.html", id=id, form=form, form2=form2)


@groups.route("/<int:id>/changelocation", methods=["POST"])
@login_required
def update_location(id):
    """
    Handles group location update with details from selected location(returned
    from location search by postcode through external API)
    """
    form = UpdateButton()
    group_location = Location.query.filter_by(group_id=id)

    if form.validate_on_submit():
        data = {
            "postcode": request.args["postcode"],
            "suburb": request.args["suburb"],
            "state": request.args["state"]
        }
        fields = location_schema.load(data)
        group_location.update(fields)

src/controllers/profile_controller.py
from models.Profile import Profile
from models.ProfileImage import ProfileImage
from models.Locations import Location
from main import db
from flask import (current_app, Blueprint, render_template,
                   redirect, url_for, flash, request)
from flask_login import current_user, login_required
from controllers.controller_helpers import Helpers
import boto3
from forms import (ProfileForm, ProfileImageUpload,
                   DeleteButton, SearchLocation, AddButton)

profile = Blueprint('profile', __name__, url_prefix="/web/profile")


@profile.route("/", methods=["GET"])
@login_required
def profile_page():
    """
    User profile page

    Renders profile page
    """
    user_id, profile = Helpers.retrieve_profile()
    image = None
    locations = None

    if not profile:
        return redirect(url_for("profile.profile_name"))

    if profile:
        profile_image = ProfileImage.query.filter_by(
            profile_id=profile.id).first()
        if profile_image:
            image = Helpers.retrieve_profile_picture(profile_image)
        locations = Location.query.filter_by(profile_id=profile.id).all()

    return render_template(
        "profile.html", profile=profile, image=image, locations=locations)


@profile.route("/profilename", methods=["GET", "POST"])
@login_required
def profile_name():
    """
    Profile name page - for new users.

    GET requests renders profile name page with ProfileForm
    POST requests validate form and handles confirmation of new
    user's profile name.
    """
    user_id = current_user.get_id()
    form = ProfileForm()
    if form.validate_on_submit():
        new_profile = Profile(
            name=form.profile_name.data,
            user_id=user_id
        )
        db.session.add(new_profile)
        db.session.commit()
        flash("Profile name confirmed!")
        return redirect(url_for("profile.profile_page"))
    return render_template("profile_name.html", form=form)


@profile.route("/uploadimage", methods=["GET", "POST"])
@login_required
def profile_image():
    """
    Profile image upload page

    GET requests renders profile image upload page
    with options to upload and remove profile image.
    POST requests validates profile image upload form and handles
    profile picture upload to designated AWS S3 bucket
    """
    user_id, profile = Helpers.retrieve_profile()
    delete = DeleteButton()

    form = ProfileImageUpload()
    if form.validate_on_submit():
        image = form.image.data
        filename = f"{profile.id}-profile_image"
        bucket = boto3.resource("s3").Bucket(
            current_app.config["AWS_S3_BUCKET"])
        key = f"profile_images/{filename}"
        bucket.upload_fileobj(image, key)

        # creates database link to image filename if it doesn't already exist.
        if not profile.profile_image:
            new_image = ProfileImage()
            new_image.filename = filename
            profile.profile_image = new_image
            db.session.commit()
            flash("Image upload successful")
        return redirect(url_for("profile.profile_page"))
    return render_template("image_upload.html", form=form, delete=delete)


@profile.route("/deleteimage", methods=["POST"])
@login_required
def remove_image():
    """
    Handles removal of profile image from S3 bucket
    """
    user_id, profile = Helpers.retrieve_profile()

    delete = DeleteButton()
    if delete.validate_on_submit():
        if profile.profile_image:
            bucket = boto3.resource("s3").Bucket(
                current_app.config["AWS_S3_BUCKET"])
            filename = profile.profile_image.filename
            bucket.Object(f"profile_images/{filename}").delete()
            db.session.delete(profile.profile_image)
            db.session.commit()
            flash("Image removed")
    return redirect(url_for("profile.profile_page"))


@profile.route("/locationsearch", methods=["GET", "POST"])
@login_required
def profile_locations():
    """
    Location search page

    GET requests render search page starting with a postcode search option,
    followed by search results after postcode search completed.
    POST requests handles location search by postcode using an external
    API (postcodeAPI).
    """
    form = SearchLocation()
    form2 = AddButton()

    if form.validate_on_submit():
        data = Helpers.location_search(form.postcode.data)
        if not data:
            flash("No locations found. Try another postcode.")
        return render_template(
            "locations.html", form=form, data=data, form2=form2)
    return render_template("locations.html", form=form)


@profile.route("/addlocation", methods=["POST"])
@login_required
def add_location():
    """
    Handles logic for associating a selected location(returned from
    location search) to a user profile.
    """
    user_id, profile = Helpers.retrieve_profile()
    form = AddButton()

    if form.validate_on_submit():
        postcode = request.args["postcode"]
        suburb = request.args["suburb"]
        state = request.args["state"]

        profile_location = Location.query.filter_by(
            suburb=suburb, profile_id=profile.id).first()
        if not profile_location:
            new_location = Location()
            new_location.postcode = postcode
            new_location.suburb = suburb
            new_location.state = state
            new_location.profile_id = profile.id
            profile.locations.append(new_location)
            db.session.commit()
            flash("Suburb added!")
        elif profile_location:
            flash("Suburb already associated with your profile")
    return redirect(url_for("profile.profile_page"))

src/templates/comment.html
{% extends "base.html" %}

{% block content %}
<div class="add-name">
    <form class="form-horizontal" method="POST" action="{{ url_for('posts.post_comment', id=id) }}">
        {{ form.csrf_token }}    
        <div class="form-group">
            {{ form.comment.label(class="col-sm-2") }}
            <div class="col-sm-10">
                {{ form.comment(class="form-control") }}
                {{ form.submit(class="btn btn-primary gp-update") }}
            </div>
        </div>
    </form>
</div>

{% endblock %}

src/templates/create_group.html
{% extends "base.html" %}

{% block content %}
{% if not data %}
<div class="add-name">
    <form class="form-horizontal" method="POST" action="{{ url_for('groups.create_group') }}">
        {{ form.csrf_token }}

        <div class="form-group">
            {{ form.postcode.label(class="col-sm-2") }}
            <div class="col-sm-10">
                {{ form.postcode(class="form-control")}}
            </div>
            <div class="col-sm-10">
                {{ form.submit(class="btn btn-primary gp-update") }}
            </div>
        </div>
    </form>
</div>
{% elif data %}
<div class="add-name">
    <form class="form-horizontal" method="POST" action="{{ url_for('groups.create_group', locations=form2.group_location, data=data) }}">
        {{ form2.csrf_token }}
        <div class="form-group">
            {{ form2.group_name.label(class="col-sm-2") }}
            <div class="col-sm-10">
                {{ form2.group_name(class="form-control") }}
            </div>
            {{ form2.group_description.label(class="col-sm-2") }}
            <div class="col-sm-10">
                {{ form2.group_description(class="form-control") }}
            </div>
            <label class="col-sm-2">Location</label>
            <div class="col-sm-10">
                {% for item in form2.group_location %}
                <div class="form-check">
                    {{ item(class="form-check-input") }}
                    {{ item.label(class="form-check-label") }}
                </div>
                {% endfor %}
            </div>
            {{ form2.submit(class="btn btn-primary gp-update") }}
        </div>
    </form>
</div>
{% endif %}
{% endblock %}

src/templates/group_location.html
{% extends "base.html" %}
{% block content %}
<div class="add-name">
    <form class="form-horizontal" method="POST" action="{{ url_for('groups.update_group_location', id=id) }}">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.postcode.label(class="col-sm-2") }}
            <div class="col-sm-10">
                {{ form.postcode(class="form-control") }}
                {{ form.submit(class="btn btn-primary add-name") }}
            </div>
        </div>
    </form>
</div>
{% if data %}
<div >
    <div class="table-responsive location-table">
        <table class="table">
            <thead>
                <tr>
                    <th>Postcode</th>
                    <th>Suburb</th>
                    <th>State</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for location in data %}
                <tr>
                    <td>{{ location["postcode"] }}</td>
                    <td>{{ location["name"] }}</td>
                    <td>{{ location["state"]["abbreviation"] }}</td>
                    <td>
                        <form method="POST" action="{{ url_for('groups.update_location', id=id, postcode=location['postcode'], suburb=location['name'], state=location['state']['abbreviation']) }}">
                            {{ form2.csrf_token }}
                            {{ form2.submit(class="btn btn-primary add-location") }}
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

src/templates/group_search.html
{% extends "base.html" %}

{% block content %}
<div class="add-name">
    <form class="form-horizontal" method="POST" action="{{ url_for('groups.search_group') }}">
        {{ form.csrf_token }}    
        <div class="form-group">
            <label class="col-sm-2">Search Field</label>
            <div class="col-sm-10">
                <div class="dropdown search-options">
                    {{ form.field(class="btn btn-primary dropdown-toggle") }}
                </div>
                {{ form.keyword(class="form-control") }}
            </div>
        </div>
        {{ form.submit(class="btn btn-primary gp-update") }}
    </form>
</div>

{% if groups | length > 0 %}
<div class="profile-location search-results">
    <div class="table-responsive location-table">
        <table class="table">
            <thead>
                <tr>
                    <th>Group</th>
                    <th>Postcode</th>
                    <th>Location</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for group in groups %}
                <tr>
                    <td><a href="{{ url_for('groups.group_details', id=group.id) }}">{{ group.name }}</a></td>
                    <td>{{ group.postcode }}</td>
                    <td>{{ group.suburb }}, {{ group.state }}</td>
                    <td class="actions">
                        <form method="POST" action="{{ url_for('groups.join_group', id=group.id) }}">
                            {{ form2.csrf_token }}
                            {{ form2.submit(class="btn btn-primary") }}
                        </form>    
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

src/templates/groups.html
{% extends "base.html" %}
{% block content %}

{% if groups %}
<div class="profile-location">
    <h3>My Groups</h3>
    <div class="table-responsive location-table">
        <table class="table">
            <thead>
                <tr>
                    <th>Group</th>
                    <th>Postcode</th>
                    <th>Location</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for group in groups %}
                <tr>
                    <td><a href="{{ url_for('groups.group_details', id=group.id) }}">{{ group.name }}</a></td>
                    <td>{{ group.postcode }}</td>
                    <td>{{ group.suburb }}, {{ group.state }}</td>
                    {% if group.admin %}
                    <td class="actions">
                        <div class="dropdown"><button class="btn btn-light dropdown-toggle" aria-expanded="false" data-toggle="dropdown" type="button">Actions&nbsp;</button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{{ url_for('groups.update_group', id=group.id)}}">Update</a>
                                <form method="POST" action="{{ url_for('groups.delete_group', id=group.id) }}">
                                    {{ form3.csrf_token }}
                                    {{ form3.submit(class="btn btn-primary table-delete") }}
                                </form>            
                            </div>
                        </div>
                    </td>
                    {% elif not group.admin %}
                    <td class="actions">
                        <form method="POST" action="{{ url_for('groups.unjoin_group', id=group.id) }}">
                            {{ form2.csrf_token }}
                            {{ form2.submit(class="btn btn-primary") }}
                        </form>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}

<div class="profile-location">
    <h3>Recommendations</h3>
    <div class="table-responsive location-table">
        <table class="table">
            <thead>
                <tr>
                    <th>Group</th>
                    <th>Postcode</th>
                    <th>Location</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for group in recommendations %}
            {% if group %}            
                <tr>
                    <td><a href="{{ url_for('groups.group_details', id=group.id) }}">{{ group.name }}</a></td>
                    <td>{{ group.postcode }}</td>
                    <td>{{ group.suburb }}, {{ group.state }}</td>
                    <td class="actions">
                        <form method="POST" action="{{ url_for('groups.join_group', id=group.id) }}">
                            {{ form.csrf_token }}
                            {{ form.submit(class="btn btn-primary") }}
                        </form>                
                    </td>
                </tr>
            {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="group-options">
        <a class="btn btn-primary options-button" role="button" href="{{ url_for('groups.create_group') }}">Create New Group</a>
        <a class="btn btn-primary options-button" role="button" href="{{ url_for('groups.search_group') }}">Search Group</a>
    </div>
</div>

{% endblock %}

src/templates/image_upload.html
{% extends "base.html" %}
{% block content %}

<div class="add-name">

    <div class="form-group">
        <div class="col-sm-10">
            <form class="form-horizontal" method="POST" enctype="multipart/form-data" action="{{ url_for('profile.profile_image') }}">
                {{ form.csrf_token }}
                {{ form.image(class="form-control-file") }}
                <span>{{ ",".join(form.image.errors) }}</span>
                {{ form.submit(class="btn btn-primary upload-photo") }}
            </form>
            <form method="POST" action="{{ url_for('profile.remove_image') }}" >
                {{ delete.csrf_token }}
                {{ delete.submit(class="btn btn-primary upload-photo") }}
            </form>        
        </div>
    </div>
</div>

{% endblock %}

src/templates/locations.html
{% extends "base.html" %}
{% block content %}

<div class="add-name">
    <form class="form-horizontal" method="POST" action="{{ url_for('profile.profile_locations') }}">
        {{ form.csrf_token }}

        <div class="form-group">
            {{ form.postcode.label(class="col-sm-2") }}
            <div class="col-sm-10">
                {{ form.postcode(class="form-control") }}
                {{ form.submit(class="btn btn-primary add-name") }}
        </div>
    </form>
</div>
{% if data %}
    <div>
        <div class="table-responsive location-table">
            <table class="table">
                <thead>
                    <tr>
                        <th>Postcode</th>
                        <th>Suburb</th>
                        <th>State</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for location in data %}
                    <tr>
                        <td>{{ location["postcode"] }}</td>
                        <td>{{ location["name"] }}</td>
                        <td>{{ location["state"]["abbreviation"] }}</td>
                        <td>
                            <form method="POST" action="{{ url_for('profile.add_location', postcode=location['postcode'], suburb=location['name'], state=location['state']['abbreviation']) }}">
                                {{ form2.csrf_token }}
                                {{ form2.submit(class="btn btn-primary add-location") }}
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endif %}

{% endblock %}

src/templates/navbar.html
<nav class="navbar navbar-light navbar-expand-md navigation-clean">
    <div class="container"><a class="navbar-brand" href="{{ url_for('groups.groups_page') }}">MyLocale</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{{ url_for('profile.profile_page') }}">Profile</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('groups.groups_page') }}">Groups</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

src/templates/profile.html
{% extends "base.html" %}

{% block content %}

<div class="profile">
    {% if not image %}
    <a href="{{ url_for('profile.profile_image') }}"><img class="profile-photo" src="{{ url_for('static', filename='assets/img/default.png') }}" /></a>
    {% elif image %}
    <a href="{{ url_for('profile.profile_image') }}"><img class="profile-photo" src="{{ image }}" /></a>
    {% endif %}
    <h1 class="profile-name">{{ profile.name }}</h1>
</div>
<div class="profile-location">
    <h3>My Neighborhoods</h3>
    {% if locations %}
    <div class="table-responsive location-table">
        <table class="table">
            <thead>
                <tr>
                    <th>Postcode</th>
                    <th>Suburb</th>
                    <th>State</th>
                </tr>
            </thead>
            <tbody>
                {% for location in locations %} 
                <tr>
                    <td>{{ location.postcode }}</td>
                    <td>{{ location.suburb }}</td>
                    <td>{{ location.state }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
    <a class="btn btn-primary add-location" role="button" href="{{ url_for('profile.profile_locations') }}">Add Location</a>
</div>
{% endblock %}